### ISSUE TITLE
[1.20.1] Crash on Dedicated Servers

### ISSUE THREAD

**Issue by Talan67** [ShadowKing21228/Bauble-Mounts#1]
When bauble mounts is put on a server it causes a crash.

Debug Log: https://gist.github.com/Talan67/361b5a3a12ae2f95fbff1fc7f1c160b5
Latest Log: https://gist.github.com/Talan67/585e7c5887b04fa96b08407442739b45

**Comment by ShadowKing21228** [comment]
Thanks for finding bug. This has been fixed in the new version 1.5.1
https://www.curseforge.com/minecraft/mc-mods/bauble-mounts/files/5789668
