### ISSUE TITLE
Mixin crashes game on launch

### ISSUE THREAD

**Issue by Not-February** [ShadowKing21228/Bauble-Mounts#3]
[latest.log](https://github.com/user-attachments/files/17607456/latest.log)

Occurs with only this mod + its dependencies installed

Versions used:

Minecraft 1.20.1
Forge 47.3.0
Curios API 5.11.0
SDM UI Lib 1.8.2
Architectury 9.2.14
Bauble Mounts 0.5.2

**Comment by ShadowKing21228** [comment]
Thanks for bug report, fix in new version (already released in Modrinth and Curse)
