### ISSUE TITLE
Mod causes blocks placed in world to not stack with the same block in inventory.

### ISSUE THREAD

**Issue by Starkilla55** [ShadowKing21228/Bauble-Mounts#5]
I believe this mod is adding some NBT Tag to every block placed, which makes it not able to stack with the blocks in your inventory. Spent HOURS trying to find the culprit of this bug. It was this. Thought you should know. Words for google search; minecraft blocks not stacking with themselves. minecraft stack issue, minecraft block stacking bug.

**Comment by ShadowKing21228** [comment]
Which version of the mod and on which version of the game did this error occur? It has been fixed in recent versions.

**Comment by Starkilla55** [comment]
1.18.2 Forge

**Comment by ShadowKing21228** [comment]
This happened because the mod version 1.18.2 is outdated, and I have not yet migrated the mod to this version.
A version with bug fixes and new features is already available in Modrinth and Curse. (1.0.0-1.18.2)
